services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: memo-backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app
      - huggingface-cache:/root/.cache/huggingface

    command:
      uvicorn main:app --host 0.0.0.0 --reload

volumes:
  huggingface-cache: